from pathlib import Path
import logging
import secrets
from pydantic_settings import BaseSettings, SettingsConfigDict

class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file='.env', env_file_encoding='utf-8', extra='ignore')
    DATABASE_URL: str = 'postgresql://valsec:valsec_local_change_me@localhost:5432/valsec'
    REDIS_URL: str = 'redis://localhost:6379/0'
    OLLAMA_URL: str = 'http://localhost:11434'
    OLLAMA_AUTH_TOKEN: str = ''
    INFERENCE_TIMEOUT_MULTIPLIER: float = 1.5
    MAX_CONCURRENT_AUDITS: int = 5
    ENABLE_CREDENTIAL_VAULT: bool = False
    CREDENTIAL_VAULT_KEY: str = ''
    DISCOVERY_MAX_DEPTH: int = 3
    DISCOVERY_MAX_DEVICES: int = 25
    OLLAMA_MAPPING_BATCH_SIZE: int = 24
    OLLAMA_MAPPING_MAX_CANDIDATES: int = 96
    SECRET_KEY: str = 'change-me-in-production'
    VALSEC_ENV: str = 'development'
    ALLOWED_HOSTS: str = 'localhost,127.0.0.1'
    CORS_ORIGINS: str = 'http://localhost:3000,http://127.0.0.1:3000'
    REQUIRE_AUTH: bool = False
    PASSWORD_MIN_LENGTH: int = 10
    SESSION_TTL_HOURS: int = 72
    SESSION_COOKIE_NAME: str = 'valsec_session'
    SESSION_COOKIE_SECURE: bool = False
    SESSION_COOKIE_SAMESITE: str = 'lax'
    SESSION_COOKIE_DOMAIN: str = ''
    OTP_TTL_SECONDS: int = 300
    OTP_LENGTH: int = 6
    OTP_MAX_ATTEMPTS: int = 5
    OTP_RESEND_COOLDOWN_SECONDS: int = 60
    EMAIL_BACKEND: str = 'console'
    EMAIL_DEV_CONSOLE_OK: bool = False
    EMAIL_FROM: str = 'Valsec <no-reply@valsec.local>'
    SMTP_HOST: str = ''
    SMTP_PORT: int = 587
    SMTP_USER: str = ''
    SMTP_PASSWORD: str = ''
    SMTP_STARTTLS: bool = True
    GOOGLE_CLIENT_ID: str = ''
    GOOGLE_CLIENT_SECRET: str = ''
    GITHUB_CLIENT_ID: str = ''
    GITHUB_CLIENT_SECRET: str = ''
    APP_URL: str = 'http://localhost:3000'
    OAUTH_STATE_TTL_SECONDS: int = 600
    MAX_AUDITS_PER_MONTH: int = 100
    RATE_LIMIT_SIGNUP: int = 10
    RATE_LIMIT_SIGNUP_WINDOW: int = 3600
    RATE_LIMIT_LOGIN: int = 10
    RATE_LIMIT_LOGIN_WINDOW: int = 900
    RATE_LIMIT_OTP_RESEND: int = 5
    RATE_LIMIT_OTP_RESEND_WINDOW: int = 3600

settings = Settings()
_WEAK_SECRETS = {'change-me-in-production','change_me_in_production','change_me_to_a_long_random_string','change_me','change-me'}
_AUTOGEN_PREFIX = 'valsec-autogen-'

def _secret_is_weak():
    value=settings.SECRET_KEY.strip()
    return value in _WEAK_SECRETS or 'change' in value.lower() or len(value)<32

def _credential_vault_key_is_weak():
    value=settings.CREDENTIAL_VAULT_KEY.strip()
    return not value or value in _WEAK_SECRETS or 'change' in value.lower() or len(value)<32

def is_production():
    return settings.VALSEC_ENV.strip().lower() in {'production','prod'} or settings.REQUIRE_AUTH or settings.SESSION_COOKIE_SECURE

def _secret_key_file():
    return Path(__file__).resolve().parent.parent/'.secret_key'

def secret_is_autogenerated():
    return settings.SECRET_KEY.strip().startswith(_AUTOGEN_PREFIX)

def ensure_secret_key():
    if not _secret_is_weak() or is_production(): return
    path=_secret_key_file()
    try:
        existing=path.read_text().strip() if path.exists() else ''
        if existing:
            settings.SECRET_KEY=existing
            return
        settings.SECRET_KEY=_AUTOGEN_PREFIX+secrets.token_urlsafe(48)
        path.write_text(settings.SECRET_KEY)
        path.chmod(0o600)
    except OSError:
        settings.SECRET_KEY=_AUTOGEN_PREFIX+secrets.token_urlsafe(48)

def validate_startup_security():
    problems=[]
    if _secret_is_weak(): problems.append('SECRET_KEY must be at least 32 characters and must not be a placeholder')
    if settings.ENABLE_CREDENTIAL_VAULT and _credential_vault_key_is_weak():
        problems.append('CREDENTIAL_VAULT_KEY must be at least 32 characters and must not be a placeholder')
    if 'valsec_local_change_me' in settings.DATABASE_URL: problems.append('DATABASE_URL contains the shipped local PostgreSQL password')
    if secret_is_autogenerated() and is_production(): problems.append('Set an explicit SECRET_KEY for production')
    if not problems: return
    if is_production(): raise RuntimeError(f'Refusing insecure production startup (VALSEC_ENV={settings.VALSEC_ENV}): '+'; '.join(problems))
    log=logging.getLogger('valsec.startup')
    for problem in problems: log.warning('Local development default: %s',problem)
